### ISSUE TITLE
开发经验

### ISSUE THREAD

**Issue by Emily90** [LazyFE/Task#28]
## 图片与图片之间有缝隙

``` css
display: block;　/* 将图片设置为块级元素　*/
height: 356px;   /* 将图片高度裁剪为偶数，避免奇数　*/
```
## input 输入光标不垂直居中或高度过高

``` css
padding: 0 10px; /* 使用padding实现垂直居中，避免使用line-height　*/
```
## display: flex 兼容写法

> 参考链接:http://www.w3cplus.com/css3/using-flexbox.html

``` css
display: -webkit-box;      /* OLD - iOS 6-, Safari 3.1-6 */
display: -moz-box;         /* OLD - Firefox 19- (buggy but mostly works) */
display: -ms-flexbox;      /* TWEENER - IE 10 */
display: -webkit-flex;     /* NEW - Chrome */
display: flex;             /* NEW, Spec - Opera 12.1, Firefox 20+ */
```

``` css
-webkit-box-flex: 1;      /* OLD - iOS 6-, Safari 3.1-6 */
-moz-box-flex: 1;         /* OLD - Firefox 19- */
width: 20%;               /* For old syntax, otherwise collapses. */ ( 可以写 0 )
-webkit-flex: 1;          /* Chrome */
-ms-flex: 1;              /* IE 10 */
flex: 1;                  /* NEW, Spec - Opera 12.1, Firefox 20+ */
```
## flex 不能与 inline-block 同时出现

> 以下内容转自: http://qingui.uis.cc/experience.php
## 移动端禁止选中内容

如果你不想用户可以选中页面中的内容，那么你可以在css中禁掉：

``` css
.user-select-none {
  -webkit-user-select: none;  /* Chrome all / Safari all */
  -moz-user-select: none;     /* Firefox all （移动端不需要） */
  -ms-user-select: none;      /* IE 10+ */     
}
```
## 手机拍照和上传图片

``` html
<!-- 选择照片 -->
<input type="file" accept="image/*">
<!-- 选择视频 -->
<input type="file" accept="video/*">
```

使用总结：
ios 有拍照、录像、选取本地图片功能
部分android只有选取本地图片功能
## 高频触发事件 采用事件节流 或加以控制

比如要绑定一个touchmove的事件，正常的情况下类似这样

``` javascript
$('div').on('touchmove', function(){
   //.….code
});
```

而如果中间的code需要处理的东西多的话，FPS就会下降影响程序顺滑度，而如果改成这样

``` javascript
$('div').on('touchmove', function(){
   setTimeout(function(){
   //.….code
   },0);
});
```

把代码放在setTimeout中，会发现程序变快.
## 移动端 HTML5 audio autoplay 失效问题

由于自动播放网页中的音频或视频，会给用户带来一些困扰或者不必要的流量消耗，所以苹果系统和安卓系统通常都会禁止自动播放和使用 JS 的触发播放，必须由用户来触发才可以播放。

解决方法思路：先通过用户 touchstart 触碰，触发播放并暂停（音频开始加载，后面用 JS 再操作就没问题了）。

``` javascript
document.addEventListener('touchstart', function () {
  document.getElementsByTagName('audio')[0].play();
  document.getElementsByTagName('audio')[0].pause();
});
```
## 利用padding或margin得百分比特性做响应式元素

padding 和 margin得 top 和 bottom值设置百分比参数，百分比是相对于宽度计算得距离，利用此特性有助于移动端定位元素位置。
## 使伪类:active生效

要CSS伪类 :active 生效，只需要给 document 绑定 touchstart 或 touchend 事件 解决方法：加入下方js，激活:active。

``` javascript
document.addEventListener('touchstart',function(){},false);
```
## 添加分享到朋友圈缩略图

微信分享链接时，自动抓取缩略图方法： 需要一张300*300的图片, 并添加在 body 下，微信会自动抓取这张图来作为缩略图显示，格式如下：

``` html
<div id="wx_pic" style="display:none;">
  <img src="http://www0.autoimg.cn/topic/2015/3/peugeot3008/m/assets/images/share.jpg">
</div>
```

> 以上内容转自: http://qingui.uis.cc/experience.php

**Comment by Emily90** [comment]
## input或select 输入框内的文字被截断

解决方法
line-height 不要设置成1

**Comment by Emily90** [comment]
## 显示两行文字，多余两行省略

``` css
p {
   overflow : hidden;
   text-overflow: ellipsis;
   display: -webkit-box;
   -webkit-line-clamp: 2;
   -webkit-box-orient: vertical;
}
```

## 显示单行文字，超出部分省略

``` css
p {
  text-overflow: ellipsis;
  word-wrap: break-word;
  white-space: nowrap;
  overflow: hidden;
}
```

## 相关插件
1. [Clamp.js](https://github.com/josephschmitt/Clamp.js)
2. [jQuery.dotdotdot](https://github.com/FrDH/jQuery.dotdotdot)
